#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--linux-packages "linux-image linux-headers" \
	--source false \
        --iso-application "PureOS-3.0 Linux" \
        --iso-publisher "Purism" \
        --iso-volume "Pure-OS-3.0 Live" \
"${@}"
